name: simple_dart_multilang_object_table
description: Multilang Object Table Component
version: 0.1.3
repository: https://github.com/simple-dart/multilang_object_table
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_multilang_checkbox: ^0.0.2
  simple_dart_multilang_controller: ^0.0.2
  simple_dart_multilang_table: ^0.1.2
  simple_dart_object_table: ^0.1.4
  simple_dart_table: ^0.1.2
  simple_dart_ui_core: ^0.0.3

